apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: y0zs76hel-go-gitops
  description: This is GitOps manifest for y0zs76hel-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=y0zs76hel-go
    backstage.io/kubernetes-id: y0zs76hel-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: y0zs76hel-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:y0zs76hel-go
